# Generated by Django 2.0.7 on 2018-07-13 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='claimed_user',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='app.UserAssociation'),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='question',
            field=models.ForeignKey(on_delete='CASCADE', to='app.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='site',
            field=models.ForeignKey(on_delete='CASCADE', to='app.StackExchangeSite'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='app.Transaction'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userassociation',
            name='site',
            field=models.ForeignKey(on_delete='CASCADE', to='app.StackExchangeSite'),
        ),
    ]
