# Generated by Django 2.0.7 on 2018-07-14 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180713_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=65),
        ),
        migrations.AlterField(
            model_name='balance',
            name='user',
            field=models.OneToOneField(on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bounty',
            name='amount',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=65),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=30, default=0, max_digits=65),
        ),
    ]
